name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 64.227.147.124
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/week-25-ci-next-app

            echo "Pulling latest code"
            git pull origin main

            echo "Installing deps"
            pnpm install

            echo "Building app"
            pnpm run build

            echo "Restarting services"
            pm2 restart fe-server || pm2 start fe-server
            pm2 restart http-server || pm2 start http-server
            pm2 restart ws-server || pm2 start ws-server
