name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.206.134.230
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/bookbook

            echo "Pulling latest code"
            git pull origin main

            echo "Installing deps"
            pnpm install

            echo "Building app"
            pnpm run build

            echo "Restarting services"
            pm2 restart frontend || pm2 start frontend
            pm2 restart http || pm2 start http
            pm2 restart ws || pm2 start ws
