name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster

    steps:
      - name: SSH Into server
      - run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
          ssh -i ~/ssh_key root@54.206.134.230
          cd bookbook/ && git pull
          pnpm install
          pnpm run build
          pm2 restart frontend
          pm2 restart http
          pm2 restart ws
